---
author: Oleksandra Dreval
title: Motion Graphics Designer/Graphic Designer
pdf-engine: latexmk #other engines throw an error :(
tagline: |
  Driven by curiosity and a passion for crafting immersive motion experiences, I specialize in creating compelling visual narratives across TV, digital, and interactive platforms
format:
  sidebar-cv-pdf: default
cvimage:
  file: title.jpg
  trim:
    left: 100 
    bottom: 265
    right: 50
    top: 50
cvfooter:
  left: "https://oleksadreval.com"
  right: "https://www.artstation.com/aleksandradreval"
color:
  main: "F6E7CB" #without '#'
  accent: "000000"
  bgdark: "FFFFFF"
  bglight: "000000"
  titletext: "000000"
  maintext: "000000"
  star: "000000"
  dates: "000000"
cvfont: gillius #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - name: Contact
    items:
      - icon: canadian-maple-leaf #from fontawesome5
        text: Port Coquitlam, BC, Canada
      - mail: oleksadreval@gmail.com
      - icon: atlas
        text: https://oleksadreval.com
        href: https://oleksadreval.com
      - icon: linkedin
        text: "linkedin.com/in/oleksadreval"
        href: https://www.linkedin.com/in/oleksandra-dreval-ba740a149/
  - name: Software
    items:
      - icon: film
        text: After Effects
        stars: 5
      - icon: file-video
        text: Premiere Pro
        stars: 5
      - icon: draw-polygon
        text: Cinema 4D + Redshift
        stars: 5
      - icon: shapes
        text: Autodesk Maya
        stars: 3
      - icon: gamepad
        text: Zbrush
        stars: 3
      - icon: edit
        text: Unreal Engine
        stars: 4
      - icon: magic
        text: Photoshop
        stars: 5
        nowrap: true
      - icon: bezier-curve
        text: Illustrator
        stars: 5
      - icon: code
        text: HTML/CSS
        stars: 5
      - icon: figma
        text: Figma
        stars: 5
      - icon: indent
        text: InDesign
        stars: 5
      - icon: laptop-code
        text: XD
        stars: 5
  - name: Skills
    items:
      - icon: file-video
        text: Motion Graphics
        nowrap: true # no newline
      - icon: desktop
        text: Graphic Design
        nowrap: true
      - icon: paint-brush
        text: Adobe CS
        nowrap: true
      - icon: video
        text: 2D/2.5/3D animation
        nowrap: true
      - icon: record-vinyl
        text: Styling
        nowrap: true
      - icon: eye
        text: Branding and visual identity
        nowrap: true
      - icon: indent
        text: Print production/prepress
        nowrap: true
      - icon: ellipsis-h
        text: Tracking
        nowrap: true
      - icon: draw-polygon
        text: Rotoscoping
        nowrap: true
      - icon: laptop-code
        text: UI/UX (mobile/desktop)
        nowrap: true
      - icon: adjust
        text: Color
        nowrap: true
      - icon: sticky-note
        text: Composition
        nowrap: true
      - icon: font
        text: Typography
        nowrap: true
      - icon: sliders-h
        text: Layout
        nowrap: true
      - icon: handshake
        text: Flexibility
        nowrap: true
      - icon: lightbulb
        text: Creativity
        nowrap: true
  - name: Awards
    items:
      - icon: photo-video
        text: American Inst. of Graphic Arts (AIGA)
      - icon: palette
        text: Universal Phoenix Group
      - icon: paint-brush
        text: NVidia
execute:
  echo: false
keep-tex: true
---


```{r}
#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0(x, collapse = ", "))
    res <- paste0(res, "{",tbl[[details]],"}")
    cat(res, sep = "\n")
}
```

# Summary

Motion Graphics Designer | 2D/3D Animator | Visual Storyteller

# Experience


```{r}
#| label: experience
#| output: asis
tibble::tribble(
    ~role, ~institution, ~dates, ~details, ~tasks,
    "Lead Designer @ 3AG Systems", "Burnaby, BC", "09/2021 - 01/2025", "Marketing Department", c("Designed and animated motion content for social media{,} web{,} and digital campaigns", "Developed motion storytelling materials that elevated brand engagement by 35\\%", "Led the motion-based branding assets redesign{,} boosting sales by 25\\%", "Collaborated cross-functionally to conceptualize and execute engaging visual identities"),
    "Graphic Designer @ mimik Technologies Inc", "Vancouver, BC", "04/2021 - 09/2021", "Marketing Department", c("Created high-impact motion graphics for corporate branding and social media campaigns", "Designed UI/UX{,} animations{,} and micro-interactions to enhance digital experiences", "Produced brand-aligned motion content that elevated customer engagement by 17\\%"),
    "3D Generalist @ Wawybrain Studios LLC", "Albuquerque, NM", "2020 - 2021", "Game Design", c("Conceptualized and animated character-driven motion sequences for interactive media", "Developed visually rich 3D models{,} textures{,} and assets for storytelling", "Created hand-drawn and digital illustrations to support creative narratives"),
    "Motion Graphics Designer @ REELZ TV", "Albuquerque, NM", "03/2018 - 06/2020", "Marketing Department", c("Designed high-energy motion graphics for TV{,} web{,} and social media", "Developed and animated motion sequences that aligned with network branding", "Led design team in developing on-air and off-air promotional assets", "Interviewed potential recruits and provided mentorship for new team members", "Developed workflows and best practices for asset organization in database"),
    "3D Animator @ Universal Phoenix Group", "Atlanta, GA", "2017", "Game design", c("Designed and animated 3D characters and assets for interactive media", "Created high-quality textures and materials to enhance realism and visual appeal", "Collaborated with motion designers to integrate animations into digital experiences"),
    "Graphic Designer @ RightBrain Training", "Kyiv", "2014 - 2017", "Marketing Department", c("Designed educational materials{,} incorporating motion elements to learning experiences")

) |>
    cvevents(when = "dates", what = "role", where = "institution", details = "tasks")
```

# Education

```{r }
#| label: education
#| output: asis
tibble::tribble(
    ~degree, ~uni, ~loc, ~dates, ~details,
    "MSc in Computer Graphics and Design", "Ukraine", "Donetsk, Ukraine", "10/2013 - 06/2016", c(""),
    "MSc in Biology", "Ukraine", "Donetsk, Ukraine", "09/2007 - 05/2012", c("")
) |>
    cvevents(when = "dates", what = "degree", where = "uni", details = "details")
```
