---
author: Oleksandra Dreval
title: Morion Graphics Designer/Graphic Designer
pdf-engine: latexmk #other engines throw an error :(
tagline: |
  I create awesome 2D/3D characters for game and animation. Besides that I am a flexible universe lover committed to learn new cool stuff and grow my skills!
format:
  sidebar-cv-pdf: default
cvimage:
  file: dog2.jpg
  trim:
    left: 0 
    bottom: 320
    right: 200
    top: 770
cvfooter:
  left: "https://oleksadreval.com"
  right: "https://www.artstation.com/aleksandradreval"
color:
  main: "FFAA00" #without '#'
  accent: "000000"
  bgdark: "000000"
  bglight: "000000"
  titletext: FFFFFF
  maintext: "000000"
  star: "000000"
  dates: "000000"
cvfont: gillius #texlive fonts like raleway,fetamont,gillius,comfortaa
cvmeta:
  - name: Contact
    items:
      - icon: canadian-maple-leaf #from fontawesome5
        text: Port Coquitlam, BC, Canada
      - mail: oleksadreval@gmail.com
      - icon: atlas
        text: https://oleksadreval.com
        href: https://oleksadreval.com
      - icon: linkedin
        text: "LinkedIn"
        href: https://www.linkedin.com/in/oleksandra-dreval-ba740a149/
  - name: Software
    items:
      - icon: magic
        text: Photoshop
        stars: 5
        nowrap: true
      - icon: bezier-curve
        text: Illustrator
        stars: 5
      - icon: film
        text: After Effects
        stars: 5
      - icon: file-video
        text: Premiere Pro
        stars: 5
      - icon: draw-polygon
        text: Cinema 4D + Red Giant
        stars: 4
      - icon: shapes
        text: Autodesk Maya
        stars: 3
      - icon: gamepad
        text: Zbrush
        stars: 3
      - icon: edit
        text: Unreal Engine
        stars: 3
      - icon: code
        text: Workflows
        stars: 5
      - icon: meteor
        text: Animation
        stars: 5
      - icon: indent
        text: InDesign
        stars: 5
      - icon: heart
        text: Human anatomy
        stars: 5
  - name: Skills
    items:
      - icon: file-video
        text: Motion Graphics
        nowrap: true # no newline
      - icon: gamepad
        text: Character Design
        nowrap: true
      - icon: bezier-curve
        text: Adobe CS
        nowrap: true
      - icon: video
        text: 2D/2.5D/3D animation
        nowrap: true
      - icon: record-vinyl
        text: Art continuity
        nowrap: true
      - icon: eye
        text: Character Modelling
        nowrap: true
      - icon: paint-brush
        text: Painting
        nowrap: true
      - icon: ellipsis-h
        text: Leadership
        nowrap: true
      - icon: sliders-h
        text: Layout
        nowrap: true
      - icon: draw-polygon
        text: Multitasking
        nowrap: true
      - icon: desktop
        text: GFX
        nowrap: true
      - icon: lightbulb
        text: Creativity
        nowrap: true
      - icon: adjust
        text: Color theory
        nowrap: true
      - icon: handshake
        text: Flexibility
        nowrap: true
      - icon: laptop-code
        text: UI/UX
        nowrap: true
      - icon: font
        text: Typography
        nowrap: true
      - icon: sticky-note
        text: Composition
        nowrap: true
  - name: Awards
    items:
      - icon: photo-video
        text: American Inst. of Graphic Arts (AIGA)
      - icon: palette
        text: Universal Phoenix Group
      - icon: paint-brush
        text: NVidia
execute:
  echo: false
keep-tex: true
---


```{r}
#| label: cvevents
cvevents <- function(tbl, when, what, where, details) {

    command_start <- "\\cvevent"

    res <- paste0(
        command_start, "{", tbl[[when]], "}", 
        "{", tbl[[what]], "}",
        "{", tbl[[where]], "}")
    
    tbl[[details]] <- sapply(tbl[[details]], function(x) paste0(x, collapse = ", "))
    res <- paste0(res, "{",tbl[[details]],"}")
    cat(res, sep = "\n")
}
```

# Summary

2D/3D character artist experienced in animation, production, games, and motion graphics.

# Experience


```{r}
#| label: experience
#| output: asis
tibble::tribble(
    ~role, ~institution, ~dates, ~details, ~tasks,
    "Character Designer @ Bonsai Animations", "Toronto, ON", "10/2024 - Present", "Game Design", c("Designed unique characters to align with project vision and style", "Produced detailed face expressions for 2D animations ensuring design consistency", "Refined character design features to enhance storytelling and audience engagement"),
    "Character Artist @ Wawybrain Studios", "Albuquerque, NM", "02/2020 - Present", "Game Design", c("Produced character design with human anatomy for animation and cinematics", "Developed concept art for characters and in-game assets", "Developed 3D models of characters with surfacing and fur", "Created graphics and illustrations to promote storytelling", "Created character and asset sketching and design following best quality standards"),
    "Lead Graphic Designer @ 3AG Systems", "Burnaby, BC", "09/2021 - 01/2025", "Marketing Department", c("Produced marketing materials from concept to delivery", "Designed UI/UX for desktop and mobile software products and web-sites", "Developed brand identity and guidelines with innovative solutions", "Created production collaterals with efficient file-building methods and workflows"),
    "Motion Graphics Designer @ REELZ TV", "Albuquerque, NM", "03/2018 - 06/2020", "Marketing Department", c("Created motion and keyart for on- and off-air graphics coherent with art direction", "Enhanced video/photo to enhance visual appeal and maintain brand identity", "Interviewed potential recruits and provided mentorship for new team members", "Developed and executed branding strategies and maintained digital assets database", "Developed workflows and best practices for asset organization in database"),
    "3D Animator @ Universal Phoenix Group", "Atlanta, GA", "05/2017 - 08/2017", "Game design", c("Animated 3D models of in-game characters using provided models and keyed lighting", "Followed production workflows for game development in collaborative setting")

) |>
    cvevents(when = "dates", what = "role", where = "institution", details = "tasks")
```

# Education

```{r }
#| label: education
#| output: asis
tibble::tribble(
    ~degree, ~uni, ~loc, ~dates, ~details,
    "MSc in Computer Graphics and Design", "Ukraine", "Donetsk, Ukraine", "10/2013 - 06/2016", c(""),
    "MSc in Biology", "Ukraine", "Donetsk, Ukraine", "09/2007 - 05/2012", c("")
) |>
    cvevents(when = "dates", what = "degree", where = "uni", details = "details")
```
